from datetime import datetime, timedelta, timezone

from app.models.news import Article


def sample_articles() -> list[Article]:
    now = datetime.now(timezone.utc)
    return [
        Article(
            id="openai-agent-2026",
            title="OpenAI expands enterprise agent platform with stronger workflow controls",
            source="TechCrunch",
            url="https://techcrunch.com",
            publishedAt=now - timedelta(minutes=18),
            category="LLMs",
            language="English",
            summary="OpenAI is positioning agentic workflows as a core enterprise layer with governance controls and safer tool execution.",
            sentiment="positive",
            country="United States",
            popularity=96,
            keywords=["OpenAI", "agents", "enterprise", "workflow"],
            companies=["OpenAI", "Microsoft"],
        ),
        Article(
            id="nvidia-supply-chain",
            title="NVIDIA AI accelerator demand reshapes global semiconductor supply chains",
            source="Reuters",
            url="https://reuters.com",
            publishedAt=now - timedelta(minutes=44),
            category="AI Hardware",
            language="English",
            summary="Cloud providers and sovereign AI programs continue to compete for GPUs, memory, packaging, and power infrastructure.",
            sentiment="neutral",
            country="United States",
            popularity=91,
            keywords=["NVIDIA", "GPU", "semiconductors", "datacenter"],
            companies=["NVIDIA", "TSMC", "SK hynix"],
        ),
        Article(
            id="google-gemini-tools",
            title="Google Gemini tooling expands across analytics and developer workflows",
            source="Google News fallback",
            url="https://news.google.com/search?q=Gemini%20AI",
            publishedAt=now - timedelta(minutes=67),
            category="AI Tools",
            language="English",
            summary="Gemini-related coverage continues to focus on productivity tooling, search experiences, and developer integrations across Google's AI stack.",
            sentiment="positive",
            country="United States",
            popularity=82,
            keywords=["Gemini", "AI tools", "Google", "productivity"],
            companies=["Google"],
        ),
        Article(
            id="anthropic-claude-enterprise",
            title="Claude adoption grows as enterprises evaluate safer AI assistants",
            source="Hacker News fallback",
            url="https://hn.algolia.com/?query=Claude%20AI",
            publishedAt=now - timedelta(minutes=94),
            category="LLMs",
            language="English",
            summary="Developer and enterprise discussions around Claude emphasize coding support, long-context workflows, and model safety for business use cases.",
            sentiment="positive",
            country="Global",
            popularity=79,
            keywords=["Claude", "Anthropic", "enterprise AI", "LLM"],
            companies=["Anthropic"],
        ),
        Article(
            id="ai-regulation-global",
            title="AI regulation updates remain a major theme across global policy discussions",
            source="GDELT fallback",
            url="https://www.gdeltproject.org/",
            publishedAt=now - timedelta(hours=2, minutes=8),
            category="AI Regulation",
            language="English",
            summary="Policy coverage continues to focus on model transparency, safety obligations, copyright, and risk controls for AI systems.",
            sentiment="neutral",
            country="Global",
            popularity=73,
            keywords=["AI regulation", "policy", "safety", "governance"],
            companies=["OpenAI", "Google", "Microsoft"],
        ),
        Article(
            id="open-source-ai-models",
            title="Open-source AI models continue to pressure proprietary LLM platforms",
            source="Reddit fallback",
            url="https://www.reddit.com/r/LocalLLaMA/",
            publishedAt=now - timedelta(hours=2, minutes=41),
            category="Open Source AI",
            language="English",
            summary="Open model communities are focusing on efficient inference, local deployment, reasoning quality, and enterprise privacy advantages.",
            sentiment="positive",
            country="Global",
            popularity=70,
            keywords=["open source", "LLM", "local AI", "inference"],
            companies=["Meta", "Mistral AI", "DeepSeek"],
        ),
        Article(
            id="ai-coding-agents",
            title="AI coding agents move from autocomplete toward repository-level automation",
            source="Hacker News fallback",
            url="https://news.ycombinator.com/",
            publishedAt=now - timedelta(hours=3, minutes=15),
            category="AI Coding",
            language="English",
            summary="Developer tools are shifting from single-line completion toward agents that can inspect codebases, run tests, and prepare pull requests.",
            sentiment="positive",
            country="Global",
            popularity=76,
            keywords=["AI coding", "agents", "developer tools", "automation"],
            companies=["GitHub", "OpenAI", "Anthropic"],
        ),
        Article(
            id="robotics-generative-ai",
            title="Robotics teams combine vision-language models with warehouse automation",
            source="Google News fallback",
            url="https://news.google.com/search?q=robotics%20generative%20AI",
            publishedAt=now - timedelta(hours=4, minutes=2),
            category="Robotics",
            language="English",
            summary="Robotics coverage highlights multimodal AI systems that can interpret instructions, handle exceptions, and support logistics automation.",
            sentiment="neutral",
            country="Japan",
            popularity=65,
            keywords=["robotics", "generative AI", "automation", "vision-language model"],
            companies=["Toyota", "SoftBank Robotics"],
        ),
    ]
